package entity;
// Generated Oct 31, 2016 11:51:55 PM by Hibernate Tools 4.3.1



/**
 * DeliveryCost generated by hbm2java
 */
public class DeliveryCost  implements java.io.Serializable {


     private int deliveryId;
     private String zoneName;
     private double deliveryCost;

    public DeliveryCost() {
    }

    public DeliveryCost(int deliveryId, String zoneName, double deliveryCost) {
       this.deliveryId = deliveryId;
       this.zoneName = zoneName;
       this.deliveryCost = deliveryCost;
    }
   
    public int getDeliveryId() {
        return this.deliveryId;
    }
    
    public void setDeliveryId(int deliveryId) {
        this.deliveryId = deliveryId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public double getDeliveryCost() {
        return this.deliveryCost;
    }
    
    public void setDeliveryCost(double deliveryCost) {
        this.deliveryCost = deliveryCost;
    }




}


