package entity;
// Generated Oct 31, 2016 11:51:55 PM by Hibernate Tools 4.3.1



/**
 * ProOrderDetails generated by hbm2java
 */
public class ProOrderDetails  implements java.io.Serializable {


     private int orderDetailsId;
     private int orderId;
     private int proId;
     private int proQty;

    public ProOrderDetails() {
    }

    public ProOrderDetails(int orderDetailsId, int orderId, int proId, int proQty) {
       this.orderDetailsId = orderDetailsId;
       this.orderId = orderId;
       this.proId = proId;
       this.proQty = proQty;
    }
   
    public int getOrderDetailsId() {
        return this.orderDetailsId;
    }
    
    public void setOrderDetailsId(int orderDetailsId) {
        this.orderDetailsId = orderDetailsId;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getProId() {
        return this.proId;
    }
    
    public void setProId(int proId) {
        this.proId = proId;
    }
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }




}


