package entity;
// Generated Oct 31, 2016 11:51:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProOrder generated by hbm2java
 */
public class ProOrder  implements java.io.Serializable {


     private int orderId;
     private int proId;
     private int userId;
     private Date orderDate;
     private int orderQty;
     private double totalPrice;
     private String orderStatus;
     private int delivaryId;

    public ProOrder() {
    }

    public ProOrder(int orderId, int proId, int userId, Date orderDate, int orderQty, double totalPrice, String orderStatus, int delivaryId) {
       this.orderId = orderId;
       this.proId = proId;
       this.userId = userId;
       this.orderDate = orderDate;
       this.orderQty = orderQty;
       this.totalPrice = totalPrice;
       this.orderStatus = orderStatus;
       this.delivaryId = delivaryId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getProId() {
        return this.proId;
    }
    
    public void setProId(int proId) {
        this.proId = proId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public int getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(int orderQty) {
        this.orderQty = orderQty;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    public int getDelivaryId() {
        return this.delivaryId;
    }
    
    public void setDelivaryId(int delivaryId) {
        this.delivaryId = delivaryId;
    }




}


