package entity;
// Generated Oct 31, 2016 11:51:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ShopUser generated by hbm2java
 */
public class ShopUser  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String password;
     private String email;
     private Date regDate;
     private String contuctNo;
     private int roleId;

    public ShopUser() {
    }

    public ShopUser(int userId, String userName, String password, String email, Date regDate, String contuctNo, int roleId) {
       this.userId = userId;
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.regDate = regDate;
       this.contuctNo = contuctNo;
       this.roleId = roleId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getContuctNo() {
        return this.contuctNo;
    }
    
    public void setContuctNo(String contuctNo) {
        this.contuctNo = contuctNo;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }




}


