package entity;
// Generated Oct 31, 2016 11:51:55 PM by Hibernate Tools 4.3.1



/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private int subCatId;
     private int catId;
     private String subCatName;
     private String subCatDesc;

    public SubCategory() {
    }

    public SubCategory(int subCatId, int catId, String subCatName, String subCatDesc) {
       this.subCatId = subCatId;
       this.catId = catId;
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
    }
   
    public int getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(int subCatId) {
        this.subCatId = subCatId;
    }
    public int getCatId() {
        return this.catId;
    }
    
    public void setCatId(int catId) {
        this.catId = catId;
    }
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }

    public void setCategory(Category category) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


